name: app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  file_picker: ^5.3.2
  flutter_pdfview: ^1.3.1
  firebase_storage: ^11.2.3
  firebase_database: ^10.2.3
  path_provider: ^2.0.15
  pdf_render: ^1.4.0
  get: ^4.6.5
  pdf: ^3.4.1



  flutter:
    sdk: flutter
  dynamic_color: ^1.6.6
  google_fonts: ^5.1.0
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
